package com.pl.gdl.common.model;

import com.pl.gdl.common.enums.DataType;
import java.io.Serializable;
import java.util.Objects;

public class ColumnInfo implements Serializable {
    private int columnIndex;
    private String columnName;
    private String dataTypeName = "string";
    private int jdbcType = java.sql.Types.VARCHAR;
    private int columnLength = 255;
    private int decimalDigits = 0;
    private String remarks = "";
    private boolean nullable = true;
    private String defaultValue;
    private boolean partition = false;
    private boolean primaryKey = false;
    private boolean autoGenerated = false;
    private int primaryKeyIndex = 0;

    public ColumnInfo() {}

    public ColumnInfo(String columnName, String dataTypeName) {
        this.columnName = columnName;
        this.dataTypeName = dataTypeName;
        DataType dt = DataType.fromString(dataTypeName);
        this.jdbcType = dt.getJdbcType();
    }

    public ColumnInfo(String columnName, String dataTypeName, int columnLength, String remarks) {
        this(columnName, dataTypeName);
        this.columnLength = columnLength;
        this.remarks = remarks;
    }

    public int getColumnIndex() { return columnIndex; }
    public void setColumnIndex(int columnIndex) { this.columnIndex = columnIndex; }

    public String getColumnName() { return columnName; }
    public void setColumnName(String columnName) { this.columnName = columnName; }

    public String getDataTypeName() { return dataTypeName; }
    public void setDataTypeName(String dataTypeName) {
        this.dataTypeName = dataTypeName;
        if (dataTypeName != null) {
            DataType dt = DataType.fromString(dataTypeName);
            this.jdbcType = dt.getJdbcType();
        }
    }

    public int getJdbcType() { return jdbcType; }
    public void setJdbcType(int jdbcType) { this.jdbcType = jdbcType; }

    public int getColumnLength() { return columnLength; }
    public void setColumnLength(int columnLength) { this.columnLength = columnLength; }

    public int getDecimalDigits() { return decimalDigits; }
    public void setDecimalDigits(int decimalDigits) { this.decimalDigits = decimalDigits; }

    public String getRemarks() { return remarks; }
    public void setRemarks(String remarks) { this.remarks = remarks; }

    public boolean isNullable() { return nullable; }
    public void setNullable(boolean nullable) { this.nullable = nullable; }

    public String getDefaultValue() { return defaultValue; }
    public void setDefaultValue(String defaultValue) { this.defaultValue = defaultValue; }

    public boolean isPartition() { return partition; }
    public void setPartition(boolean partition) { this.partition = partition; }

    public boolean isPrimaryKey() { return primaryKey; }
    public void setPrimaryKey(boolean primaryKey) { this.primaryKey = primaryKey; }

    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public int getPrimaryKeyIndex() { return primaryKeyIndex; }
    public void setPrimaryKeyIndex(int primaryKeyIndex) { this.primaryKeyIndex = primaryKeyIndex; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ColumnInfo that = (ColumnInfo) o;
        return Objects.equals(columnName, that.columnName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(columnName);
    }

    @Override
    public String toString() {
        return "ColumnInfo{" +
                "name='" + columnName + '\'' +
                ", type='" + dataTypeName + '\'' +
                '}';
    }
}
